version: "3.3"

networks:
  network_docker_dev:

services:
  db_mysql8:
    container_name: db_mysql8
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: app_root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      - network_docker_dev

  app_php:
    container_name: app_php
    build:
      args:
        uid: 1000
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 8080:8080      
    depends_on:
      - db_mysql8
    networks:
      - network_docker_dev

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db_mysql8
      PMA_USER: app
      PMA_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app_root
    depends_on:
      - db_mysql8
    networks:
      - network_docker_dev